### PR TITLE
Few Fixes

### PR DESCRIPTION
**Pull request by vigneshshanmugam**
+ SSL Timing
+ Removed bookmarlet hack
+ Scroll bar overflow

### CODE REVIEW

**Comment by andydavies** [comment]
Can you change this

```if(resources[n].name.indexOf('waterfall.js') !== 0){```

to 

```if(resources[n].name.indexOf('/waterfall.js') !== -1){```

i.e. insert the / before the filename and check against -1 rather than 0

**Comment by vigneshshanmugam** [comment]
Done.

**Comment by andydavies** [comment]
Thanks

**Comment by andydavies** [comment]
There's a bug somewhere in the original waterfall code that results in the bars overflowing the overlay, I'm going to fix this before pushing this PR to the GH branch

**Comment by vigneshshanmugam** [comment]
Sure :+1:

**Pull request merged**
