### PR TITLE
Few Fixes

### PR DESCRIPTION
**Pull request by vigneshshanmugam**

### CODE REVIEW

**Comment by vigneshshanmugam** [comment]
Removed the bookmarklet script by name. Executing in the console was removing the last resource from the waterfall always, So removed that hack.

**Comment by vigneshshanmugam** [comment]
I don't think tcpDuration changes with the introduction of SSL timings.

Tested the same on https://developers.facebook.com..

### Waterfall
waterfall

### Console Output

console

**Comment by vigneshshanmugam** [comment]
@andydavies What do you suggest?.

**Comment by andydavies** [comment]
If we take the example above and flattened it out then the order the TCP and SSL segments are painted becomes important - what we want is them to consistently appear as segments on the same line and I'd pick WebPageTest style waterfalls as the model.

So TCP segment becomes the 3 - way handshake e.g. connect Start to SSL start, and the SSL segment is SSL Start to connect end - the 3 way handshake must occur before the SSL negotiation can take place (at least with HTTP, not sure how things like QUIC change this ATM)

**Comment by vigneshshanmugam** [comment]
Yeah got the idea Andy. Sent the final PR.

**Comment by vigneshshanmugam** [comment]
@andydavies  Any problem with this?. Please suggest.

**Comment by paulirish** [comment]
I tested this PR and it worked great for me.

vignesh can you rebaseline it for easy resolving?

**Comment by andydavies** [comment]
In the process of testing this I found the bars are overflowing the side of the chart (and a few other issues with the original code) so gave been sucked into that rabbit hole!

My only query with this PR is the check for waterfall.js - should it check for the GH url or just check for /waterfall.js so it works locally etc.

**Comment by paulirish** [comment]
> - should it check for the GH url or just check for /waterfall.js so it works locally etc.

+1 to checking for "waterfall.js".  I had been using it in a devtools snippet but otherwise it woulda caught me.

**Comment by vigneshshanmugam** [comment]
@paulirish Sure will rebase it and give the final PR.

@andydavies  - Yeah fixed the overflow issue of the scrollbar. Will give a final PR with the check for waterfall.js

**Comment by vigneshshanmugam** [comment]
I will give a new PR with all the fixes. I have lost my local repo and couldn't able to recover it.

Sorry for the mess.

**Comment by vigneshshanmugam** [comment]
#14 Check this new PR with everything covered.

**Pull request closed without merging**
